(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
Needs["XMGR`"];


(* ::Input::Initialization:: *)
Clear[CopyBEAMDPToDir];
CopyBEAMDPToDir[InDir_String]:=Module[{
UseTargetNM,GetDirNM,BDPNM="beamdp.exe"
},
UseTargetNM=FileNameJoin[{InDir,BDPNM}];
If[FileExistsQ[UseTargetNM],Return[True];];
GetDirNM=FileNameJoin[{Environment["HEN_HOUSE"],"bin","gnu_win32",BDPNM}];
StringMatchQ[CopyFile[GetDirNM,UseTargetNM],UseTargetNM]
];
(*
CopyBEAMDPToDir["C:\\PhaseSpace\\Varian600C\\"]
*)


(* ============================================================================= *)
(* Spectrum Scripts - These contain the templates for the specific BEAMDP 
					  functions. There are replacements to be made before they 
					  can be executed. 
		File names cannot get to long or BEAMDP will present an IO error (it 
		can't find the file). 
	After each script text, is a set of default replacement rules. Replace the 
	specific fields for your application and then apply the default replacement 
	rules. That way all the fields in the input file will be defined.
*)
(* ============================================================================= *)
SpectrumBEAMDPScriptText = {"n"
   , "3"
   , "PARTICLETYPE, XMIN, XMAX, YMIN, YMAX"
   , "NUMBINS,EMIN,EMAX"
   , "0,0,0"
   , "PHSPFILENAME.egsphspPHNUM"
   , "PHSPFILENAME_PARTICLENAMESpectrum_YMINToYMAX_PHNUM_NUMBINS.xmgr"
   , "1"
   , "0"
   , "0"
   , "0"
   , "\n"};
SpectrumBEAMDPDefaultReplacementRules = {
   "PHNUM" -> "1"
   , "XMIN" -> "-1.0"
   , "XMAX" -> "1.0"
   , "YMIN" -> "-16.0"
   , "YMAX" -> "16.0"
   , "NUMBINS" -> "100"
   , "EMIN" -> "0.00"
   , "EMAX" -> "6.00"
   };

(* ============================================================================= *)
PositionBEAMDPScriptText = {"n"
   , "9"
   , "PARTICLETYPE, XMIN, XMAX, YMIN, YMAX"
   , "0, 6"
   , "0, 0, 0"
   , "PHSPFILENAME.egsphspPHNUM"
   , "PHSPFILENAME_Position_PARTICLENAME_PHNUM.xmgr"
   , "NUMBERPARTICLES"
   , "0"
   , "0"
   , "\n"};
PositionBEAMDPDefaultReplacementRules = {
   "PHNUM" -> "1"
   , "XMIN" -> "-1.0"
   , "XMAX" -> "1.0"
   , "YMIN" -> "-16.0"
   , "YMAX" -> "16.0"
   , "NUMBINS" -> "100"
   , "EMIN" -> "0.00"
   , "EMAX" -> "6.00"
   };

(* ============================================================================= *)
MeanEnergyBEAMDPScriptText = {
   "n"
   , "5"
   , "2"
   , "NUMBINS, ZEROISXONEISY, PARTICLETYPE, XMIN, XMAX, YMIN, YMAX, "
   , "0, 0, 0"
   , "1, "
   , "PHSPFILENAME.egsphspPHNUM"
   , "PHSPFILENAME_MeanEnergy_PARTICLENAME_PHNUM_NUMBINS.xmgr"
   , "1"
   , "0"
   , "0"
   , "\n"};
MeanEnergyBEAMDPDefaultReplacementRules = {
   "PHNUM" -> "1"
   , "XMIN" -> "-1.0"
   , "XMAX" -> "1.0"
   , "YMIN" -> "-16.0"
   , "YMAX" -> "16.0"
   , "NUMBINS" -> "64"
   , "ZEROISXONEISY" -> "1"
   };
(* ============================================================================= *)
FluenceBeamDPScript = {"n"
   , "1"
   , "2,"
   , "NUMBINS,ZEROISXONEISY,PARTICLETYPE,XMIN, XMAX, YMIN, YMAX, "
   , "0, 0, 0"
   , "PHSPFILENAME.egsphspPHNUM"
   , "PHSPFILENAME_Fluence_PARTICLENAME_PHNUM_NUMBINS.xmgr"
   , "1"
   , "1"
   , "0"
   , "0"
   , "\n"};
FluenceBeamDPDefaultReplacementRules = {
   "PHNUM" -> "1"
   , "XMIN" -> "-1.0"
   , "XMAX" -> "1.0"
   , "YMIN" -> "-1.0"
   , "YMAX" -> "1.0"
   , "NUMBINS" -> "64"
   , "ZEROISXONEISY" -> "0"
   };
(* ============================================================================= *)
DumpParticlesBeamDPScript = {"n"
   , "11"
   , "NUMBERPARTICLES, 0"
   , "PHSPFILENAME.egsphspPHNUM"
   , "0"
   , "0"
   , "\n"};
(* ============================================================================= *)
DumpZLastBeamDPScript = {"n"
   , "7"
   , "PARTICLETYPE, XMIN, XMAX, YMIN, YMAX"
   , "NUMBERPARTICLES, 0, 0.5"
   , "0, 0, 0"
   , "PHSPFILENAME.egsphspPHNUM"
   , "PHSPFILENAME_ZLast_PARTICLENAME_PHNUM.xmgr"
   , "1"
   , "0"
   , "0"
   , "\n"};
(* ============================================================================= *)
AngularDistributionScriptText = {"n"
   , "6"
   , "PARTICLETYPE, 0, 1, 0, 0"
   , "NUMBINS, ANGLEMIN, ANGLEMAX"
   , "0, 6"
   , "0, 0, 0"
   , "PHSPFILENAME.egsphspPHNUM"
   , "PHSPFILENAME_AngDist_PARTICLENAME_PHNUM.xmgr"
   , "1"
   , "0"
   , "0"
   , "0", "\n"
   };
AngularBeamDPDefaultReplacementRules = {
   "NUMBINS" -> "100"
   , "ANGLEMIN" -> "0"
   , "ANGLEMAX" -> "90"
   , "" -> ""
   , "" -> ""
   , "" -> ""
   };
(* ============================================================================= *)
(* ============================================================================= *)


(* ::Input::Initialization:: *)
Clear[RunBEAMDPScript];
Options[RunBEAMDPScript]={
};
RunBEAMDPScript[InDir_String,InScriptText_List,OptionsPattern[]]:=Module[{
UseFN,OldDir
,BDPNM="beamdp.exe"
},
{
}=OptionValue[{}];

CopyBEAMDPToDir[InDir];
OldDir=Directory[];
SetDirectory[InDir];
UseFN="Temp_"<>DateString[{"Year","Month","Day","Hour","Minute","Second"}]<>".script";
Export[UseFN,InScriptText,"Text"];
Run[BDPNM<>" < "<>UseFN];
DeleteFile[UseFN];
SetDirectory[OldDir];
];
(*
RunBEAMDPScript["F:\\PhaseSpace\\Varian600C\\"
,TestScript
];
MyFuncPlotMultipleXmgrData[{"F:\\PhaseSpace\\Varian600C\\Varian_Clinac_600C_6MV_10x10_MeanEnergy_Photon_1_64.xmgr"}]
*)



